[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit AHTX0 @ ^2.0.5
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.0.4

; If your ESP32-C3 Super Mini variant needs a different board profile,
; you can switch `board` to another ESP32-C3 board supported by PlatformIO.
